name: sampleapp
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_datepicker: ^22.1.39

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.1
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  provider: ^6.0.5
  font_awesome_flutter: ^10.5.0  # FontAwesomeIcons gives you access to many more icons.
  google_fonts: ^5.1.0
  rxdart: ^0.27.7
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

  build_runner: ^2.4.6
  json_serializable: ^6.7.1

#flutter:
 # uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/
  #   - assets/covers/
  #   - assets/congrats.gif
flutter:   
  uses-material-design: true
  assets:
        - assets/images/png_logo.png
        - assets/images/pinpan_head.png
        - assets/images/pinpan_walk.png
        - assets/images/pinpan.png
        - assets/images/worried_pinpan.png
        - assets/images/pinpan_thinhead.png
        - assets/images/ladypic.jpg
        - assets/images/Doc1.jpeg
        - assets/images/Doc2.jpeg
        - assets/images/Doc3.jpeg
        - assets/images/Doc4.jpeg
        - assets/images/Doc5.jpeg
       # - assets/image/yourSecondImage.jpg
        
